/**
 * GDG on Campus · VIT Chennai
 * Technical Recruitment 2026 — Comprehensive Questionnaire Definition
 *
 * All questions carry:
 * - id: Stable canonical ID
 * - departmentId: Department UUID or 'general'
 * - section: 'personal' | 'why_gdg' | 'technical_interests' | 'department' | 'projects' | 'reflection'
 * - type: 'short-text' | 'long-text' | 'single-choice' | 'multiple-choice' | 'url'
 * - label: Clear human-readable question title
 * - helperText: Contextual guidance and beginner reassurance
 * - placeholder: Helpful example answer snippet
 * - required: Boolean
 * - order: Numerical order within section
 * - version: Schema version number (1)
 * - options: Array of strings (for single/multiple choice)
 * - name: Same as label for backwards-compatibility
 * - questionText: Same as label
 * - questionId: Same as id
 */

export const QUESTIONNAIRE_VERSION = "2026.1";

// -------------------------------------------------------------
// SECTION 2: WHY GDG? (Community & Motivation Questions)
// -------------------------------------------------------------
export const WHY_GDG_QUESTIONS = [
  {
    id: "general.motivation",
    questionId: "general.motivation",
    name: "What interests you about joining GDG on Campus · VIT Chennai?",
    questionText: "What interests you about joining GDG on Campus · VIT Chennai?",
    label: "What interests you about joining GDG on Campus · VIT Chennai?",
    section: "why_gdg",
    departmentId: "general",
    type: "long-text",
    required: true,
    order: 1,
    version: 1,
    helperText:
      "Tell us what genuinely interests you — learning, building projects, meeting other developers, contributing to events, exploring a new technology, or something else.",
    placeholder: "Share what draws you to the student developer community and what you hope to experience...",
  },
  {
    id: "general.learning_goal",
    questionId: "general.learning_goal",
    name: "What is one technical skill or technology you want to learn this year?",
    questionText: "What is one technical skill or technology you want to learn this year?",
    label: "What is one technical skill or technology you want to learn this year?",
    section: "why_gdg",
    departmentId: "general",
    type: "short-text",
    required: true,
    order: 2,
    version: 1,
    helperText: "Can be anything — a language, framework, tool, concept, or library you're curious about.",
    placeholder: "e.g. Next.js, Flutter, Solidity, Neural Networks, Docker, Figma...",
  },
  {
    id: "general.contribution_goal",
    questionId: "general.contribution_goal",
    name: "What would you like to build or contribute to if you join GDG?",
    questionText: "What would you like to build or contribute to if you join GDG?",
    label: "What would you like to build or contribute to if you join GDG?",
    section: "why_gdg",
    departmentId: "general",
    type: "long-text",
    required: true,
    order: 3,
    version: 1,
    helperText: "Think of an app, a community website, a hackathon project, or an open-source tool.",
    placeholder: "Describe a project idea or how you'd like to collaborate with fellow members...",
  },
  {
    id: "general.explain_concept",
    questionId: "general.explain_concept",
    name: "Tell us about something technical you learned recently. How would you explain it to another student who has never seen it before?",
    questionText: "Tell us about something technical you learned recently. How would you explain it to another student who has never seen it before?",
    label: "Tell us about something technical you learned recently. How would you explain it to another student who has never seen it before?",
    section: "why_gdg",
    departmentId: "general",
    type: "long-text",
    required: true,
    order: 4,
    version: 1,
    helperText: "We value clear communication and the ability to break complex ideas into approachable concepts.",
    placeholder: "Pick any concept (big or small) and explain it simply using an everyday analogy...",
  },
  {
    id: "general.teamwork",
    questionId: "general.teamwork",
    name: "Tell us about a time you worked with another person or team to solve a problem.",
    questionText: "Tell us about a time you worked with another person or team to solve a problem.",
    label: "Tell us about a time you worked with another person or team to solve a problem.",
    section: "why_gdg",
    departmentId: "general",
    type: "long-text",
    required: true,
    order: 5,
    version: 1,
    helperText: "Can be a college lab assignment, hackathon, school project, or any collaborative effort.",
    placeholder: "Explain the goal, how you divided work, how you communicated, and what you learned...",
  },
  {
    id: "general.community_contribution",
    questionId: "general.community_contribution",
    name: "How would you contribute to a technical community even outside writing code?",
    questionText: "How would you contribute to a technical community even outside writing code?",
    label: "How would you contribute to a technical community even outside writing code?",
    section: "why_gdg",
    departmentId: "general",
    type: "multiple-choice",
    required: true,
    order: 6,
    version: 1,
    options: [
      "Helping others learn and debug",
      "Writing clear documentation and tutorials",
      "Organising technical workshops and hackathons",
      "Designing UI and visual content",
      "Testing applications and giving constructive feedback",
      "Mentoring and guiding junior peers",
      "Building internal tools and community bots",
      "I am still figuring this out and eager to explore",
    ],
    helperText: "Select all that apply. Technical communities thrive on diverse talents beyond just code.",
  },
  {
    id: "general.learning_by_building",
    questionId: "general.learning_by_building",
    name: "What does \"learning by building\" mean to you?",
    questionText: "What does \"learning by building\" mean to you?",
    label: "What does \"learning by building\" mean to you?",
    section: "why_gdg",
    departmentId: "general",
    type: "long-text",
    required: true,
    order: 7,
    version: 1,
    helperText: "GDG is centered around hands-on experimentation rather than passive theory.",
    placeholder: "Share your perspective on experimenting, making mistakes, and learning by creating...",
  },
];

// -------------------------------------------------------------
// SECTION 3: TECHNICAL INTERESTS & CAMPUS PROJECT
// -------------------------------------------------------------
export const TECHNICAL_INTEREST_QUESTIONS = [
  {
    id: "general.interest_areas",
    questionId: "general.interest_areas",
    name: "Which areas are you most interested in exploring?",
    questionText: "Which areas are you most interested in exploring?",
    label: "Which areas are you most interested in exploring?",
    section: "technical_interests",
    departmentId: "general",
    type: "multiple-choice",
    required: true,
    order: 1,
    version: 1,
    options: [
      "Web Development (Frontend / Backend)",
      "App Development (Android / Flutter)",
      "Data Science & AI / ML",
      "Blockchain & Web3",
      "Game Development",
      "Competitive Programming & DSA",
      "Open Source & Git Collaboration",
      "UI/UX Design & User Research",
      "Cloud Infrastructure & DevOps",
      "Cybersecurity",
      "Other",
    ],
    helperText: "Select all domains you are curious about or wish to learn.",
  },
  {
    id: "general.primary_interest",
    questionId: "general.primary_interest",
    name: "Which of these are you most excited to learn about?",
    questionText: "Which of these are you most excited to learn about?",
    label: "Which of these are you most excited to learn about?",
    section: "technical_interests",
    departmentId: "general",
    type: "single-choice",
    required: true,
    order: 2,
    version: 1,
    options: [
      "Web Development",
      "App Development",
      "Data Science & AI",
      "Blockchain",
      "Game Development",
      "Competitive Programming",
      "Open Source",
      "UI/UX Design",
    ],
    helperText: "Pick your single top interest. This helps leads understand what excites you most.",
  },
  {
    id: "general.campus_project",
    questionId: "general.campus_project",
    name: "GDG is planning a one-week student project for the VIT Chennai campus. What would you build, and how would you approach it?",
    questionText: "GDG is planning a one-week student project for the VIT Chennai campus. What would you build, and how would you approach it?",
    label: "GDG is planning a one-week student project for the VIT Chennai campus. What would you build, and how would you approach it?",
    section: "technical_interests",
    departmentId: "general",
    type: "long-text",
    required: true,
    order: 3,
    version: 1,
    helperText:
      "We are interested in how you think about problems, not whether you already know every technology required. Focus on utility for VIT Chennai students.",
    placeholder: "e.g. A campus shuttle tracker, mess menu rater, room study finder, peer notes exchange...",
  },
];

// -------------------------------------------------------------
// SECTION 4: DEPARTMENT QUESTIONNAIRES (5–7 questions each)
// -------------------------------------------------------------
export const DEPARTMENT_QUESTIONNAIRES = [
  // 1. BLOCKCHAIN
  {
    departmentId: "6a89c4e2-7b19-4f32-821e-9821a41b5201",
    department: "Blockchain",
    departmentSlug: "blockchain",
    questions: [
      {
        id: "blockchain.q1",
        questionId: "blockchain.q1",
        name: "What problem does blockchain attempt to solve that a traditional centralized database may not?",
        questionText: "What problem does blockchain attempt to solve that a traditional centralized database may not?",
        label: "What problem does blockchain attempt to solve that a traditional centralized database may not?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Consider trust, decentralization, immutability, and single points of failure...",
      },
      {
        id: "blockchain.q2",
        questionId: "blockchain.q2",
        name: "What is the difference between a blockchain transaction and updating a normal database record?",
        questionText: "What is the difference between a blockchain transaction and updating a normal database record?",
        label: "What is the difference between a blockchain transaction and updating a normal database record?",
        type: "long-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Think about consensus, verification, gas/fees, and state transitions...",
      },
      {
        id: "blockchain.q3",
        questionId: "blockchain.q3",
        name: "What is a smart contract?",
        questionText: "What is a smart contract?",
        label: "What is a smart contract?",
        type: "short-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Explain in 1-2 concise sentences in your own words...",
      },
      {
        id: "blockchain.q4",
        questionId: "blockchain.q4",
        name: "Imagine GDG wants to build a certificate verification system. What information would you store on-chain and what information would you keep off-chain? Why?",
        questionText: "Imagine GDG wants to build a certificate verification system. What information would you store on-chain and what information would you keep off-chain? Why?",
        label: "Imagine GDG wants to build a certificate verification system. What information would you store on-chain and what information would you keep off-chain? Why?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Think about privacy, gas costs, storage limits, and verification requirements.",
        placeholder: "e.g. Hashes on-chain vs. full PDFs and student personal info in off-chain IPFS / storage...",
      },
      {
        id: "blockchain.q5",
        questionId: "blockchain.q5",
        name: "A blockchain application becomes expensive and slow as usage increases. What would you investigate before deciding how to improve it?",
        questionText: "A blockchain application becomes expensive and slow as usage increases. What would you investigate before deciding how to improve it?",
        label: "A blockchain application becomes expensive and slow as usage increases. What would you investigate before deciding how to improve it?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Layer 2 solutions, gas optimization in smart contracts, off-chain computation, batching...",
      },
      {
        id: "blockchain.q6",
        questionId: "blockchain.q6",
        name: "If you could build one blockchain-based project for students at VIT Chennai, what would you build?",
        questionText: "If you could build one blockchain-based project for students at VIT Chennai, what would you build?",
        label: "If you could build one blockchain-based project for students at VIT Chennai, what would you build?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Describe an innovative, student-friendly Web3 use case...",
      },
      {
        id: "blockchain.q7",
        questionId: "blockchain.q7",
        name: "Tell us about any blockchain/Web3 concept, project or experiment you have explored.",
        questionText: "Tell us about any blockchain/Web3 concept, project or experiment you have explored.",
        label: "Tell us about any blockchain/Web3 concept, project or experiment you have explored.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you haven't explored blockchain yet, describe what you would learn first and how you would approach your first small project.",
        placeholder: "Share any tutorials, testnet contracts, wallets, or your learning roadmap...",
      },
    ],
  },

  // 2. GAME DEVELOPMENT
  {
    departmentId: "9055864f-c7dc-44cd-91d5-8759d32a496a",
    department: "Game Development",
    departmentSlug: "game-development",
    questions: [
      {
        id: "gamedev.q1",
        questionId: "gamedev.q1",
        name: "What makes a game engaging rather than simply functional?",
        questionText: "What makes a game engaging rather than simply functional?",
        label: "What makes a game engaging rather than simply functional?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Consider game loop, feedback loops, audio/visual cues, difficulty curves, and player agency...",
      },
      {
        id: "gamedev.q2",
        questionId: "gamedev.q2",
        name: "What is the difference between game logic and rendering?",
        questionText: "What is the difference between game logic and rendering?",
        label: "What is the difference between game logic and rendering?",
        type: "long-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Explain how physics/state updates relate to drawing frames on screen...",
      },
      {
        id: "gamedev.q3",
        questionId: "gamedev.q3",
        name: "Imagine a game character moves differently depending on the player's frame rate. What might cause this problem?",
        questionText: "Imagine a game character moves differently depending on the player's frame rate. What might cause this problem?",
        label: "Imagine a game character moves differently depending on the player's frame rate. What might cause this problem?",
        type: "long-text",
        required: true,
        order: 3,
        version: 1,
        helperText: "Think about delta time (deltaTime) and fixed vs. variable update loops.",
        placeholder: "Describe the delta time concept or why frame-dependent movement happens...",
      },
      {
        id: "gamedev.q4",
        questionId: "gamedev.q4",
        name: "You have one week to create a small game for a GDG event. What would you build?",
        questionText: "You have one week to create a small game for a GDG event. What would you build?",
        label: "You have one week to create a small game for a GDG event. What would you build?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        placeholder: "Describe the genre, core mechanic, visual style, and win/loss condition...",
      },
      {
        id: "gamedev.q5",
        questionId: "gamedev.q5",
        name: "How would you divide the work if three students were building the game together?",
        questionText: "How would you divide the work if three students were building the game together?",
        label: "How would you divide the work if three students were building the game together?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "e.g. Mechanics/programming, art/assets/UI, level design/sound/testing...",
      },
      {
        id: "gamedev.q6",
        questionId: "gamedev.q6",
        name: "What game mechanic would you like to experiment with?",
        questionText: "What game mechanic would you like to experiment with?",
        label: "What game mechanic would you like to experiment with?",
        type: "short-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "e.g. Time manipulation, gravity flipping, procedural generation, rhythm-based movement...",
      },
      {
        id: "gamedev.q7",
        questionId: "gamedev.q7",
        name: "Tell us about a game, prototype, interactive project or game-development concept you have explored.",
        questionText: "Tell us about a game, prototype, interactive project or game-development concept you have explored.",
        label: "Tell us about a game, prototype, interactive project or game-development concept you have explored.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you have never built a game, explain how you would start learning game development (e.g. Unity, Godot, Pygame, Unreal).",
        placeholder: "Share any projects you tried, game engines explored, or tools you want to master...",
      },
    ],
  },

  // 3. APP DEVELOPMENT
  {
    departmentId: "339f0f8a-72f2-44b9-92ab-2b0d4dcfa0f6",
    department: "App Development",
    departmentSlug: "app-development",
    questions: [
      {
        id: "appdev.q1",
        questionId: "appdev.q1",
        name: "What is an API and why would a mobile application need one?",
        questionText: "What is an API and why would a mobile application need one?",
        label: "What is an API and why would a mobile application need one?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Explain how mobile apps communicate with external databases, auth services, and servers...",
      },
      {
        id: "appdev.q2",
        questionId: "appdev.q2",
        name: "What happens when a mobile application requests information from a backend server?",
        questionText: "What happens when a mobile application requests information from a backend server?",
        label: "What happens when a mobile application requests information from a backend server?",
        type: "long-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Trace the flow from user action, HTTP request, async response, parsing JSON, to updating UI state...",
      },
      {
        id: "appdev.q3",
        questionId: "appdev.q3",
        name: "What is the difference between temporary application state and persistent data?",
        questionText: "What is the difference between temporary application state and persistent data?",
        label: "What is the difference between temporary application state and persistent data?",
        type: "long-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Contrast in-memory UI variables with local storage (SQLite, Room, SharedPreferences) and remote DBs...",
      },
      {
        id: "appdev.q4",
        questionId: "appdev.q4",
        name: "Imagine GDG wants a mobile app that shows upcoming VIT Chennai events. What information would the app need and where would that information come from?",
        questionText: "Imagine GDG wants a mobile app that shows upcoming VIT Chennai events. What information would the app need and where would that information come from?",
        label: "Imagine GDG wants a mobile app that shows upcoming VIT Chennai events. What information would the app need and where would that information come from?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Think about event dates, venues, RSVP count, speaker info, caching, and push notifications.",
        placeholder: "Structure the data model and mention how the app syncs with the GDG backend...",
      },
      {
        id: "appdev.q5",
        questionId: "appdev.q5",
        name: "Users complain that the app works well on Wi-Fi but poorly on slow networks. What would you investigate?",
        questionText: "Users complain that the app works well on Wi-Fi but poorly on slow networks. What would you investigate?",
        label: "Users complain that the app works well on Wi-Fi but poorly on slow networks. What would you investigate?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Payload size, image compression, offline caching, optimistic UI, retry logic, timeout thresholds...",
      },
      {
        id: "appdev.q6",
        questionId: "appdev.q6",
        name: "If you could build one mobile application for VIT Chennai students, what would it do?",
        questionText: "If you could build one mobile application for VIT Chennai students, what would it do?",
        label: "If you could build one mobile application for VIT Chennai students, what would it do?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Describe a mobile utility tailored to solving a genuine daily campus challenge...",
      },
      {
        id: "appdev.q7",
        questionId: "appdev.q7",
        name: "Describe a mobile application or mobile-development experiment you have worked on.",
        questionText: "Describe a mobile application or mobile-development experiment you have worked on.",
        label: "Describe a mobile application or mobile-development experiment you have worked on.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you have never developed an app, describe how you would learn (e.g., Kotlin, Flutter, React Native, Swift) and build your first simple app.",
        placeholder: "Share any app you experimented with, or what framework you intend to pick up first...",
      },
    ],
  },

  // 4. UI/UX DESIGN
  {
    departmentId: "e2ed9c2c-c36c-457f-a8bb-cf2e8bc7c2e1",
    department: "UI/UX",
    departmentSlug: "ui-ux",
    questions: [
      {
        id: "uiux.q1",
        questionId: "uiux.q1",
        name: "What is the difference between UI and UX?",
        questionText: "What is the difference between UI and UX?",
        label: "What is the difference between UI and UX?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Explain user interface visual styling versus overall user flow, journey, and problem solving...",
      },
      {
        id: "uiux.q2",
        questionId: "uiux.q2",
        name: "Why is user research important before designing an interface?",
        questionText: "Why is user research important before designing an interface?",
        label: "Why is user research important before designing an interface?",
        type: "long-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Discuss user pain points, testing assumptions, validating requirements, and persona building...",
      },
      {
        id: "uiux.q3",
        questionId: "uiux.q3",
        name: "What does accessibility mean in digital product design?",
        questionText: "What does accessibility mean in digital product design?",
        label: "What does accessibility mean in digital product design?",
        type: "long-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Color contrast, keyboard navigation, screen reader support, clear touch targets, inclusive design...",
      },
      {
        id: "uiux.q4",
        questionId: "uiux.q4",
        name: "Imagine students frequently abandon a GDG registration form halfway through. How would you investigate why?",
        questionText: "Imagine students frequently abandon a GDG registration form halfway through. How would you investigate why?",
        label: "Imagine students frequently abandon a GDG registration form halfway through. How would you investigate why?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Consider analytics drop-off points, form fatigue, unclear validation errors, or mobile usability.",
        placeholder: "Explain the methods and questions you would use to identify where and why friction occurs...",
      },
      {
        id: "uiux.q5",
        questionId: "uiux.q5",
        name: "Redesign the experience of registering for a VIT Chennai technical workshop. What would you change and why?",
        questionText: "Redesign the experience of registering for a VIT Chennai technical workshop. What would you change and why?",
        label: "Redesign the experience of registering for a VIT Chennai technical workshop. What would you change and why?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Describe improvements to discoverability, 1-click registration, instant calendar sync, and ticket reminders...",
      },
      {
        id: "uiux.q6",
        questionId: "uiux.q6",
        name: "How would you decide whether a design change actually improved the user experience?",
        questionText: "How would you decide whether a design change actually improved the user experience?",
        label: "How would you decide whether a design change actually improved the user experience?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Metrics like completion rate, time on task, error frequency, user feedback surveys, and usability tests...",
      },
      {
        id: "uiux.q7",
        questionId: "uiux.q7",
        name: "Share a design, prototype, Figma project or interface you have worked on.",
        questionText: "Share a design, prototype, Figma project or interface you have worked on.",
        label: "Share a design, prototype, Figma project or interface you have worked on.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you are new to UI/UX, tell us about an app or website whose design you like and explain why it works well.",
        placeholder: "Include a Figma/Behance link or describe an interface design you admire...",
      },
    ],
  },

  // 5. DATA SCIENCE
  {
    departmentId: "c0f3b1d1-ce05-45f6-9e34-ac9443fc5fcb",
    department: "Data Science",
    departmentSlug: "data-science",
    questions: [
      {
        id: "datascience.q1",
        questionId: "datascience.q1",
        name: "What is the difference between supervised and unsupervised learning?",
        questionText: "What is the difference between supervised and unsupervised learning?",
        label: "What is the difference between supervised and unsupervised learning?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Explain labeled data and prediction (classification/regression) versus discovering patterns (clustering)...",
      },
      {
        id: "datascience.q2",
        questionId: "datascience.q2",
        name: "Why is data preprocessing important?",
        questionText: "Why is data preprocessing important?",
        label: "Why is data preprocessing important?",
        type: "long-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Discuss missing values, normalization, outliers, noise reduction, and garbage-in garbage-out...",
      },
      {
        id: "datascience.q3",
        questionId: "datascience.q3",
        name: "What is overfitting?",
        questionText: "What is overfitting?",
        label: "What is overfitting?",
        type: "short-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Define overfitting in 1-2 sentences and mention a technique to prevent it...",
      },
      {
        id: "datascience.q4",
        questionId: "datascience.q4",
        name: "Suppose GDG has attendance data from its events. What useful insights could you try to discover?",
        questionText: "Suppose GDG has attendance data from its events. What useful insights could you try to discover?",
        label: "Suppose GDG has attendance data from its events. What useful insights could you try to discover?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Think about preferred workshop timings, popular domains, retention rates, and department correlations.",
        placeholder: "List specific hypotheses or patterns you would analyze in the dataset...",
      },
      {
        id: "datascience.q5",
        questionId: "datascience.q5",
        name: "GDG wants to predict which types of events students are most likely to attend. What data would you collect?",
        questionText: "GDG wants to predict which types of events students are most likely to attend. What data would you collect?",
        label: "GDG wants to predict which types of events students are most likely to attend. What data would you collect?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Features like branch/year, past attendance, event topic, timing, prerequisite skill level...",
      },
      {
        id: "datascience.q6",
        questionId: "datascience.q6",
        name: "How would you communicate a data-driven finding to someone who has no data science background?",
        questionText: "How would you communicate a data-driven finding to someone who has no data science background?",
        label: "How would you communicate a data-driven finding to someone who has no data science background?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Explain using clean visual charts, actionable takeaways, and plain English without heavy math jargon...",
      },
      {
        id: "datascience.q7",
        questionId: "datascience.q7",
        name: "Describe a data science, analytics, AI or machine learning project you have explored.",
        questionText: "Describe a data science, analytics, AI or machine learning project you have explored.",
        label: "Describe a data science, analytics, AI or machine learning project you have explored.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you are new to data science, describe a dataset you would like to explore and what questions you would want to answer from it.",
        placeholder: "Share any exploratory analysis, Kaggle dataset, Python notebook, or idea you're excited to try...",
      },
    ],
  },

  // 6. COMPETITIVE PROGRAMMING
  {
    departmentId: "3e9ac635-01d4-495e-aa87-a7335a2403c2",
    department: "Competitive Programming",
    departmentSlug: "competitive-programming",
    questions: [
      {
        id: "cp.q1",
        questionId: "cp.q1",
        name: "What is the difference between an array and a linked list?",
        questionText: "What is the difference between an array and a linked list?",
        label: "What is the difference between an array and a linked list?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Compare contiguous vs. non-contiguous memory, random access time vs. insertion/deletion cost...",
      },
      {
        id: "cp.q2",
        questionId: "cp.q2",
        name: "What does O(n log n) mean?",
        questionText: "What does O(n log n) mean?",
        label: "What does O(n log n) mean?",
        type: "short-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Explain time complexity scaling and name a common algorithm with this complexity (e.g. Merge Sort)...",
      },
      {
        id: "cp.q3",
        questionId: "cp.q3",
        name: "When might BFS be preferred over DFS?",
        questionText: "When might BFS be preferred over DFS?",
        label: "When might BFS be preferred over DFS?",
        type: "long-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Finding the shortest path in unweighted graphs, level-order processing, avoiding infinite depth loops...",
      },
      {
        id: "cp.q4",
        questionId: "cp.q4",
        name: "Given an array and a target value, how would you approach finding two numbers whose sum equals the target?",
        questionText: "Given an array and a target value, how would you approach finding two numbers whose sum equals the target?",
        label: "Given an array and a target value, how would you approach finding two numbers whose sum equals the target?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Mention time and space complexities of different approaches (e.g., hash map O(N) vs. two-pointer sorted O(N log N)).",
        placeholder: "Walk through the brute-force approach vs. the optimal hash table or two-pointer method...",
      },
      {
        id: "cp.q5",
        questionId: "cp.q5",
        name: "You encounter a programming problem you have never seen before. What steps do you take before writing code?",
        questionText: "You encounter a programming problem you have never seen before. What steps do you take before writing code?",
        label: "You encounter a programming problem you have never seen before. What steps do you take before writing code?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Analyze constraints, identify subproblems, test manual edge cases (0, empty, large N), trace pseudocode...",
      },
      {
        id: "cp.q6",
        questionId: "cp.q6",
        name: "How do you usually improve your solution when your first approach is too slow (TLE)?",
        questionText: "How do you usually improve your solution when your first approach is too slow (TLE)?",
        label: "How do you usually improve your solution when your first approach is too slow (TLE)?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Identify nested loops, use memoization/DP, binary search on answers, prefix sums, or optimal data structures...",
      },
      {
        id: "cp.q7",
        questionId: "cp.q7",
        name: "Tell us about a programming challenge, contest, DSA problem or algorithmic concept that taught you something.",
        questionText: "Tell us about a programming challenge, contest, DSA problem or algorithmic concept that taught you something.",
        label: "Tell us about a programming challenge, contest, DSA problem or algorithmic concept that taught you something.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you are new to competitive programming, describe how you currently approach difficult programming problems.",
        placeholder: "Share an interesting problem from LeetCode, Codeforces, college labs, or a concept you enjoyed mastering...",
      },
    ],
  },

  // 7. WEB DEVELOPMENT
  {
    departmentId: "8143de1d-db17-42fa-958d-13b10804f894",
    department: "Web Development",
    departmentSlug: "web-development",
    questions: [
      {
        id: "webdev.q1",
        questionId: "webdev.q1",
        name: "What happens after you enter a URL into a browser and press Enter?",
        questionText: "What happens after you enter a URL into a browser and press Enter?",
        label: "What happens after you enter a URL into a browser and press Enter?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Explain DNS resolution, TCP handshake, HTTP/HTTPS request, server processing, and HTML/CSS/JS rendering...",
      },
      {
        id: "webdev.q2",
        questionId: "webdev.q2",
        name: "What is the difference between frontend and backend?",
        questionText: "What is the difference between frontend and backend?",
        label: "What is the difference between frontend and backend?",
        type: "long-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Explain client-side UI, interactivity, and rendering vs. server business logic, auth, and database persistence...",
      },
      {
        id: "webdev.q3",
        questionId: "webdev.q3",
        name: "What is an API?",
        questionText: "What is an API?",
        label: "What is an API?",
        type: "short-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Define REST / GraphQL APIs in 1-2 concise sentences...",
      },
      {
        id: "webdev.q4",
        questionId: "webdev.q4",
        name: "Imagine GDG is building a registration website for an event with 5,000 students trying to access it at the same time. What problems might occur?",
        questionText: "Imagine GDG is building a registration website for an event with 5,000 students trying to access it at the same time. What problems might occur?",
        label: "Imagine GDG is building a registration website for an event with 5,000 students trying to access it at the same time. What problems might occur?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Think about concurrency, database connection limits, race conditions on seat reservations, and CDN caching.",
        placeholder: "Discuss server bottlenecks, double-booking race conditions, database connection pool exhaustion, and scaling fixes...",
      },
      {
        id: "webdev.q5",
        questionId: "webdev.q5",
        name: "A website is loading very slowly. What would you check first?",
        questionText: "A website is loading very slowly. What would you check first?",
        label: "A website is loading very slowly. What would you check first?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Inspect Network tab, uncompressed large assets/images, bundle size, heavy blocking scripts, slow API endpoints...",
      },
      {
        id: "webdev.q6",
        questionId: "webdev.q6",
        name: "What would you build for GDG on Campus · VIT Chennai if you had one week and a small team?",
        questionText: "What would you build for GDG on Campus · VIT Chennai if you had one week and a small team?",
        label: "What would you build for GDG on Campus · VIT Chennai if you had one week and a small team?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Describe a web app (e.g. project showcase, interactive campus guide, technical blog platform, event tracker)...",
      },
      {
        id: "webdev.q7",
        questionId: "webdev.q7",
        name: "Describe a web project you have worked on and the hardest problem you faced.",
        questionText: "Describe a web project you have worked on and the hardest problem you faced.",
        label: "Describe a web project you have worked on and the hardest problem you faced.",
        type: "long-text",
        required: false,
        order: 7,
        version: 1,
        helperText: "Beginner fallback: If you are new to web development, explain how you would build your first simple website (e.g., using React, HTML/CSS, Tailwind, Next.js).",
        placeholder: "Tell us about a website or component you made and how you resolved an issue...",
      },
    ],
  },

  // 8. OPEN SOURCE
  {
    departmentId: "ae7db51a-c6db-4f8d-9159-40767c5354cb",
    department: "Open Source",
    departmentSlug: "open-source",
    questions: [
      {
        id: "opensource.q1",
        questionId: "opensource.q1",
        name: "What problem does Git solve?",
        questionText: "What problem does Git solve?",
        label: "What problem does Git solve?",
        type: "long-text",
        required: true,
        order: 1,
        version: 1,
        placeholder: "Version history, branching, merge conflict resolution, distributed collaboration, rollbacks...",
      },
      {
        id: "opensource.q2",
        questionId: "opensource.q2",
        name: "What is a pull request?",
        questionText: "What is a pull request?",
        label: "What is a pull request?",
        type: "short-text",
        required: true,
        order: 2,
        version: 1,
        placeholder: "Explain what a PR is and why it exists in open source workflows...",
      },
      {
        id: "opensource.q3",
        questionId: "opensource.q3",
        name: "Why is code review useful?",
        questionText: "Why is code review useful?",
        label: "Why is code review useful?",
        type: "long-text",
        required: true,
        order: 3,
        version: 1,
        placeholder: "Catching bugs before merging, knowledge sharing, maintaining coding standards, continuous learning...",
      },
      {
        id: "opensource.q4",
        questionId: "opensource.q4",
        name: "You find a bug in an unfamiliar open-source project. How would you understand the codebase before trying to fix it?",
        questionText: "You find a bug in an unfamiliar open-source project. How would you understand the codebase before trying to fix it?",
        label: "You find a bug in an unfamiliar open-source project. How would you understand the codebase before trying to fix it?",
        type: "long-text",
        required: true,
        order: 4,
        version: 1,
        helperText: "Think about reading CONTRIBUTING.md, running reproduction tests, setting breakpoints, and searching issues.",
        placeholder: "Walk through your step-by-step approach to exploring an unfamiliar repository...",
      },
      {
        id: "opensource.q5",
        questionId: "opensource.q5",
        name: "A reviewer disagrees with your implementation. How would you handle the discussion?",
        questionText: "A reviewer disagrees with your implementation. How would you handle the discussion?",
        label: "A reviewer disagrees with your implementation. How would you handle the discussion?",
        type: "long-text",
        required: true,
        order: 5,
        version: 1,
        placeholder: "Professional communication, understanding trade-offs, providing rationale constructively, making requested updates...",
      },
      {
        id: "opensource.q6",
        questionId: "opensource.q6",
        name: "What makes a good open-source contribution beyond simply writing code?",
        questionText: "What makes a good open-source contribution beyond simply writing code?",
        label: "What makes a good open-source contribution beyond simply writing code?",
        type: "long-text",
        required: true,
        order: 6,
        version: 1,
        placeholder: "Clear documentation, bug reports with reproduction steps, triaging issues, adding unit tests, reviewing other PRs...",
      },
      {
        id: "opensource.q7",
        questionId: "opensource.q7",
        name: "Have you contributed to GitHub/open-source projects before?",
        questionText: "Have you contributed to GitHub/open-source projects before?",
        label: "Have you contributed to GitHub/open-source projects before?",
        type: "single-choice",
        required: false,
        order: 7,
        version: 1,
        options: [
          "Yes, I have contributed code or docs to open-source projects",
          "I have explored projects on GitHub but have not contributed yet",
          "I am completely new to open source and would love to start",
        ],
        helperText: "If new: Tell us what kind of project or tool you would like to contribute to first.",
      },
    ],
  },
];

// -------------------------------------------------------------
// SECTION 5: PROJECTS & EXPERIENCE (Fair to Beginners)
// -------------------------------------------------------------
export const PROJECT_QUESTIONS = [
  {
    id: "projects.has_project",
    questionId: "projects.has_project",
    name: "Have you built, designed, researched or contributed to anything you're proud of?",
    questionText: "Have you built, designed, researched or contributed to anything you're proud of?",
    label: "Have you built, designed, researched or contributed to anything you're proud of?",
    section: "projects",
    departmentId: "general",
    type: "single-choice",
    required: true,
    order: 1,
    version: 1,
    options: [
      "Yes, I have a project to share",
      "Not yet, but I am currently working on something",
      "Not yet, but I am eager to start building with GDG",
    ],
    helperText: "No prior projects? That is completely fine. We value curiosity and willingness to learn.",
  },
  {
    id: "projects.name",
    questionId: "projects.name",
    name: "Project Name",
    questionText: "Project Name",
    label: "Project Name",
    section: "projects",
    departmentId: "general",
    type: "short-text",
    required: false,
    order: 2,
    version: 1,
    placeholder: "e.g. Campus Event Hub, Smart Mess Scheduler, Pathfinding Visualizer...",
  },
  {
    id: "projects.description",
    questionId: "projects.description",
    name: "What did you build / design?",
    questionText: "What did you build / design?",
    label: "What did you build / design?",
    section: "projects",
    departmentId: "general",
    type: "long-text",
    required: false,
    order: 3,
    version: 1,
    placeholder: "Explain the purpose of the project, who it was built for, and the technologies used...",
  },
  {
    id: "projects.contribution",
    questionId: "projects.contribution",
    name: "What was your contribution and what was the hardest part?",
    questionText: "What was your contribution and what was the hardest part?",
    label: "What was your contribution and what was the hardest part?",
    section: "projects",
    departmentId: "general",
    type: "long-text",
    required: false,
    order: 4,
    version: 1,
    placeholder: "Describe your specific role, the key challenges faced, and how you solved them...",
  },
  {
    id: "projects.link",
    questionId: "projects.link",
    name: "Project Link / Demo / GitHub URL",
    questionText: "Project Link / Demo / GitHub URL",
    label: "Project Link / Demo / GitHub URL",
    section: "projects",
    departmentId: "general",
    type: "short-text",
    required: false,
    order: 5,
    version: 1,
    helperText: "Don't have a live link? Completely fine — leave this blank.",
    placeholder: "https://github.com/your-username/project-repo",
  },
  {
    id: "projects.aspirational",
    questionId: "projects.aspirational",
    name: "If you haven't built a project yet, tell us what you'd like to build and how you would start.",
    questionText: "If you haven't built a project yet, tell us what you'd like to build and how you would start.",
    label: "If you haven't built a project yet, tell us what you'd like to build and how you would start.",
    section: "projects",
    departmentId: "general",
    type: "long-text",
    required: false,
    order: 6,
    version: 1,
    helperText: "Share a tool or app you'd love to build as part of the GDG student developer community.",
    placeholder: "Tell us about an idea you want to build and the skills you plan to learn...",
  },
];

// -------------------------------------------------------------
// SECTION 6: FINAL REFLECTION / ONE LAST THING
// -------------------------------------------------------------
export const REFLECTION_QUESTIONS = [
  {
    id: "reflection.community_contribution",
    questionId: "reflection.community_contribution",
    name: "If selected for GDG, what is one thing you would like to contribute to the community?",
    questionText: "If selected for GDG, what is one thing you would like to contribute to the community?",
    label: "If selected for GDG, what is one thing you would like to contribute to the community?",
    section: "reflection",
    departmentId: "general",
    type: "long-text",
    required: false,
    order: 1,
    version: 1,
    placeholder: "e.g. Conducting a workshop, building open-source tools, designing event graphics, writing guides...",
  },
  {
    id: "reflection.meaningful_experience",
    questionId: "reflection.meaningful_experience",
    name: "What would make your GDG experience meaningful to you?",
    questionText: "What would make your GDG experience meaningful to you?",
    label: "What would make your GDG experience meaningful to you?",
    section: "reflection",
    departmentId: "general",
    type: "long-text",
    required: false,
    order: 2,
    version: 1,
    placeholder: "Share what personal growth, friendships, or technical milestones you hope to achieve...",
  },
];

// -------------------------------------------------------------
// ALL GENERAL QUESTIONS AGGREGATED (For submissions & resolvers)
// -------------------------------------------------------------
export const ALL_GENERAL_QUESTIONS = [
  ...WHY_GDG_QUESTIONS,
  ...TECHNICAL_INTEREST_QUESTIONS,
  ...PROJECT_QUESTIONS,
  ...REFLECTION_QUESTIONS,
];

// Standard legacy compatibility export
export const GENERAL_QUESTIONS = ALL_GENERAL_QUESTIONS;
export const QuestionnaireData = DEPARTMENT_QUESTIONNAIRES;
